In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics  import roc_auc_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [2]:
project_path = "/home/ninja/Dropbox/ml/kaggle/machine_failure"
target_name = "Machine failure"

In [3]:
data = pd.read_csv(f"{project_path}/data/processed_train_extra.csv")

In [17]:
data

Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0                  0.395880                -0.246230                0.545416   
1                  1.469856                 1.558605                1.720308   
2                 -0.302204                -1.040358                2.051873   
3                  0.610675                 0.692284                0.026445   
4                 -1.000288                -0.679391                0.869773   
...                     ...                      ...                     ...   
136424             0.127386                 1.053251                0.069693   
136425            -1.268781                -1.040358               -0.528565   
136426             0.342182                 1.342025                0.026445   
136427             0.986567                 0.692284               -0.528565   
136428            -1.590974                -1.329132                0.264307   

        Torque [Nm]  Tool wear [min]  type_H  type_L  Machine failure  
0         -0.499711         0.556417       0       1                0  
1         -1.323028         1.494433       0       0                0  
2         -1.628831        -1.241447       0       1                0  
3          0.464745         1.447532       0       1                0  
4         -0.582043        -1.100744       0       0                0  
...             ...              ...     ...     ...              ...  
136424    -0.335048         1.650769       0       0                0  
136425     1.029305        -1.601020       1       0                0  
136426    -0.217431         1.713303       0       1                0  
136427     0.699979        -0.975676       0       1                0  
136428    -0.123338         1.947807       0       1                0  

[136429 rows x 8 columns]

In [81]:
data.columns

Index(['Air temperature [K]', 'Process temperature [K]',
       'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]', 'type_H',
       'type_L', 'Machine failure'],
      dtype='object')

In [21]:
cols = ['Air temperature [K]', 'Process temperature [K]',
       'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]']
data['0'] = data[cols[0]] / data[cols[1]]
data['1'] = data[cols[0]] / data[cols[2]]
data['2'] = data[cols[0]] / data[cols[3]]
data['3'] = data[cols[0]] / data[cols[4]]
data['4'] = data[cols[1]] / data[cols[2]]
data['5'] = data[cols[1]] / data[cols[3]]
data['6'] = data[cols[1]] / data[cols[4]]
data['7'] = data[cols[3]] / data[cols[4]]
data['8'] = data[cols[0]]**2
data['9'] = data[cols[1]]**2
data['10'] = data[cols[2]]**2
data['11'] = data[cols[3]]**2
data['12'] = data[cols[4]]**2

In [22]:
X = data.drop('Machine failure',axis=1)
y = data['Machine failure']

In [10]:
from sklearn.model_selection import cross_val_score
from sklearn import svm

In [8]:
clf = svm.SVC(kernel='rbf', C=1, random_state=42)
scores = cross_val_score(clf, X, y, cv=2, scoring='f1_macro')
scores

array([0.49603268, 0.49603263])

In [9]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.50 accuracy with a standard deviation of 0.00


In [23]:
train_data, test_data = train_test_split(data, test_size = 0.25)

In [24]:
train_data['Machine failure'].value_counts(normalize=True)

0    0.98447
1    0.01553
Name: Machine failure, dtype: float64

In [25]:
test_data['Machine failure'].value_counts(normalize=True)

0    0.983611
1    0.016389
Name: Machine failure, dtype: float64

In [26]:
X_train = train_data.drop(target_name,axis=1)
y_train = train_data[target_name]

X_test = test_data.drop(target_name,axis=1)
y_test = test_data[target_name]

In [27]:
model = RandomForestClassifier(n_estimators=300,n_jobs=-1,max_leaf_nodes=500,min_samples_leaf=6)
model.fit(X_train,y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

print(roc_auc_score(y_train,y_train_pred))
print(roc_auc_score(y_test,y_test_pred))

0.889493614107852
0.8853757068333179


In [ ]:
0.7117928613459414
0.647491094863142

In [ ]:
# from sklearn.metrics import get_scorer_names
# get_scorer_names()

In [29]:
clf = RandomForestClassifier(n_estimators=500,n_jobs=-1,max_leaf_nodes=500,min_samples_leaf=6)
scores = cross_val_score(clf, X, y, cv=2, scoring='roc_auc')
scores

array([0.96546718, 0.96121381])

In [ ]:
array([0.96550507, 0.96281803])

In [ ]:
y_train_pred = clf.predict(X_train)
y_test_pred = clf.predict(X_test)

print(roc_auc_score(y_train,y_train_pred))
print(roc_auc_score(y_test,y_test_pred))

In [ ]:
array([0.93332583, 0.92702964])

In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
clf = KNeighborsClassifier(n_neighbors=3,n_jobs=-1)
clf.fit(X_train,y_train)

y_train_pred = clf.predict(X_train)
y_test_pred = clf.predict(X_test)

print(roc_auc_score(y_train,y_train_pred))
print(roc_auc_score(y_test,y_test_pred))

0.858039966221052
0.8385152117813877
